### ISSUE TITLE
Not an issue, just curious

### ISSUE THREAD

**Issue by CosmicjLightning** [XboxChaos/nitrogen#4]
Is there anyway to port this script into java for say a minecrafter to use megalo script in within java to make mods for minecraft? It'd me more logical IMO but I dunno, sorry. Just curious.

**Comment by adierking** [comment]
Nitrogen has been out of development for over 4 years and there's nothing more that we're interested in doing. If you want to implement something like Megalo in Minecraft, I'm sure it's possible, but you're on your own. Closing.
